name: destiny_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot exposing various Destiny-related utilities.
dependencies:
  http: ^0.11.3+3
  shelf: ^0.6.5
  shelf_route: ^0.14.1
dev_dependencies:
  mockito: ^0.11.0
  test: ^0.12.13
